version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    env_file:
      - db.env
    volumes:
      - ./data/db:/var/lib/mysql

  adminer: # DBをWEBから弄るやつ
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nextcloud:
    image: nextcloud:fpm-alpine
    restart: always
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
    env_file:
      - db.env
    volumes:
      - ./data/nextcloud:/var/www/html

  web:
    image: nginx:alpine
    restart: always
    depends_on:
      - nextcloud
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nextcloud:/var/www/html
    ports:
      - 80:80
