version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hoge
    volumes:
      - ./data/db:/var/lib/mysql

  adminer: # DBをWEBから弄るやつ
    image: adminer
    restart: always
    ports:
      - 8080:8080
